
server:
  port: ${PORT:8088}

spring:
  main:
    banner-mode: off
  application:
    name: medical_app
  jpa:
    database: POSTGRESQL
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # only for dev
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/medical_app
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:123}
    driverClassName: org.postgresql.Driver

springdoc: # only for dev
  api-docs:
    path: /swagger-ui.html
  show-actuator: true

jwt:
  secret: spec
